### PR TITLE
BITMAKER-1196: Improve files generated by CLI

### PR DESCRIPTION
**Pull request by Adriana618**
### Ticket URL:
- https://tasks.bitmaker.dev/issues/1196
### Description:
- Add requirements and python fields in bitmaker.yaml
- Before deploying, check if there was a change in bitmaker.yaml and then update Dockerfile.

### CODE REVIEW

**Comment by mgonnav** [comment]
In line 31 of `bm_cli/init.py`, since the `bitmaker.yml` is now on the project's root, the message should be changed.
Also, should an exception be raised when the file `bitmaker.yml` already exists? Maybe not.

**Review by mgonnav — CHANGES_REQUESTED** [review]
.

**Comment by Adriana618** [comment]
@mgonnav If bitmaker.yml already exists is better to raise exception because avoid overwriting the file by mistake.

**Comment by mgonnav** [comment]
I mean is that if it already exists, we should do nothing about it (not overriding, simply leaving it as is). And thus, also not raise and exception.

**Comment by Adriana618** [comment]
@mgonnav  It is a way of saying that it is wrong for you to try to start a project where there is already a project started.

**Review by mgonnav — APPROVED** [review]

**Pull request merged**
